#!/usr/bin/env php
<?php
// app/console

define('ROOT_DIR', __DIR__.'/..');
define('ROOT_VENDOR', __DIR__.'/../vendor');
$loader = require_once ROOT_VENDOR.'/autoload.php';

use App\Command\Zwazo;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Zwazo);
$application->run();